# Generated by Django 5.0.4 on 2024-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_raftserver_logentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="command",
            field=models.TextField(
                default="default_command", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="index",
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
