# Generated by Django 5.0.4 on 2024-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_logentry_command_logentry_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="index",
            field=models.IntegerField(null=True),
        ),
    ]
